name: 'migration-lint'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  lint: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run lint on migration files
        uses: batista/lint-filenames@v1
        with:
            path: './migrations'
            pattern: '^[0-9]{5}_[a-z_]*\.(sql|go)$'
  sequential:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Check sequential filenames
          run: |
            const fs = require('fs');
            const path = require('path');
            const directoryPath = './migrations';
            fs.readdir(directoryPath, (err, files) => {
                if (err) {
                console.log('Unable to scan directory: ' + err);
                process.exit(1);
                }
                files.sort();
                for (let i = 0; i < files.length; i++) {
                if (parseInt(files[i].slice(0, 5)) !== i + 1) {
                    console.log(`Non-sequential filename: ${files[i]}`);
                    process.exit(1);
                }
                }
            });


